version: "3.9"
services:
#  go-app:
#    build: .
#    container_name: bankslips-app
#    depends_on:
#      - mysql-db
#    ports:
#      - "8080:8080"

  mysql-db:
    image: mysql:latest
    container_name: bankslips
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bankslips-db
    ports:
      - "3306:3306"
