version: "3.9"
services:
  mysql-db:
    image: mysql:latest
    container_name: bankslips
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bankslips-db
    ports:
      - "3306:3306"

  go-app:
    build: .
    container_name: bankslips-app
    depends_on:
      - bankslips
    ports:
      - "8080:8080"