cloud:
  aws:
    region:
      static: sa-east-1
    stack:
      auto: false
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    topic:
      arn: ${TOPIC_ARN}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

server:
  port: 8082